### ISSUE TITLE
Need Amazon Linux AMI 2016.03.0 support

### ISSUE THREAD

**Issue by alex4Zero** [retrohacker/getos#35] opened 2016-05-01 12:05 UTC
Default OS for AWS ElasticBeansTalk is Amazon Linux AMI 2016.03.0. Assume it will be great if getos will support it. Right now it is not possible to deploy packages which have dependencies from getos

**Comment by retrohacker** [comment] 2016-05-01 16:07
Hey @alex4Zero!

Thanks for testing getos on Amazon's Linux distribution!

When you say that it isn't possible to deploy packages that depend on getos to Amazon Linux, do you mean that the build fails or that getos falls back to its default case during runtime?

As for implementing this, here is a fantastic example of how support for an OS can be added: https://github.com/retrohacker/getos/pull/34/files

We require that a PR have an accompanying test to both
A) document the assumptions about the release file
B) protect your PR from regressions caused by future changes to this package

**Comment by alex4Zero** [comment] 2016-05-01 19:18
Hi, @retrohacker 
It fails exactly the same way as it was for Alpine Linux with 'Error: No unique release file found' from mongodb-download package. I plan to send PR to support Amazon's Linux soon

**Comment by alex4Zero** [comment] 2016-05-05 21:38
Hi, @retrohacker 

Sent PR #36. Could you please take a look?

**Comment by retrohacker** [comment] 2016-05-06 16:04
Landed in #36

**Closed by retrohacker** 2016-05-06 16:04 UTC
